NUMPY DAY1

In [ ]:
import numpy as np


In [ ]:
ar1=np.array([1,2,3,4,5,6])


In [ ]:
print(ar1)

[1 2 3 4 5 6]


In [ ]:
arr=np.array([1,2,3,4,5,6])
print(arr[3:6])

[4 5 6]


In [ ]:
arr2=np.array([[1,2,3],[4,5,6],[2,5,7]])
print(arr2)

[[1 2 3]
 [4 5 6]
 [2 5 7]]


In [ ]:
print(type(arr2))
print("DATA-TYPE Ar1",ar1.dtype)
print("SHAPE arr2",arr2.shape)
print("SHAPE ar1",ar1.shape)
print("SIZE ar1",ar1.size)
print("SIZE arr2",arr2.size)
print("N Dimension arr2",arr2.ndim)
print("N Dimensions ar1",ar1.ndim)
print("N bytes",ar1.nbytes)
print("N bytes",arr2.nbytes)
print("Item size",ar1.itemsize)
print("Item size",arr2.itemsize)



<class 'numpy.ndarray'>
DATA-TYPE Ar1 int64
SHAPE arr2 (3, 3)
SHAPE ar1 (6,)
SIZE ar1 6
SIZE arr2 9
N Dimension arr2 2
N Dimensions ar1 1
N bytes 48
N bytes 72
Item size 8
Item size 8


Special Arrays

In [ ]:
arr3=np.zeros((3,3),dtype=int)
print(arr3)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [ ]:
arr4=np.ones((3,3),dtype=int)
print(arr4)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


RANDOM VALUES ARRAY

In [ ]:
arr5=np.random.random((3,3))
print(arr5)

[[0.85449306 0.03360791 0.07777077]
 [0.06588052 0.00535943 0.19872785]
 [0.25957521 0.87003862 0.512522  ]]


In [ ]:
arr6=np.random.randint(1,10,(3,3))
print(arr6)

[[3 6 8]
 [5 2 5]
 [3 8 9]]


IDENTITY MATRIX

In [ ]:
arr7=np.eye(3,3)
print(arr7)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Creating Arrays WIth Linspace and Arrange

In [ ]:
arr8=np.arange(1,10,2)
print(arr8)

[1 3 5 7 9]


In [ ]:
arr9=np.linspace(1,10,10)
print(arr9)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


SLICING

In [ ]:
arr10=np.array([[1,2,3],[4,5,6],[7,8,9],[27,83,973]])
print(arr10)
print("\n")
print(arr10[1:])
print("\n")
print(arr10[:3])
print("\n")
print(arr10[:,:])
print("\n")
print(arr10[1:3,1:5])
print("\n")
print("strides:",arr10[0:2,1:3])


[[  1   2   3]
 [  4   5   6]
 [  7   8   9]
 [ 27  83 973]]


[[  4   5   6]
 [  7   8   9]
 [ 27  83 973]]


[[1 2 3]
 [4 5 6]
 [7 8 9]]


[[  1   2   3]
 [  4   5   6]
 [  7   8   9]
 [ 27  83 973]]


[[5 6]
 [8 9]]


strides: [[2 3]
 [5 6]]


Masking

In [ ]:
arr11=np.array([1,2,3,4,5,6,7,8,9])
mask=np.array([1,0,1,1,1,0,])
print(arr11[mask])


[2 1 2 2 2 1]
